"""empty message

Revision ID: 2fe7e0ef6086
Revises: 24084250cbed
Create Date: 2018-10-06 19:14:22.898828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fe7e0ef6086'
down_revision = '24084250cbed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_abc', table_name='users')
    op.drop_column('users', 'abc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('abc', mysql.VARCHAR(length=32), nullable=False))
    op.create_index('ix_users_abc', 'users', ['abc'], unique=False)
    # ### end Alembic commands ###
